---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: volsync-system
  name: volsync-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/part-of: volsync
        control-plane: controller-manager
    spec:
      containers:
        - name: kube-rbac-proxy
          image: quay.io/brancz/kube-rbac-proxy:v0.18.2@sha256:7de54b6dedc8006ffd447267b826eb417a648c00f2b735b6d313395411803719
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --tls-min-version=VersionTLS12
            - --v=0
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
        - name: manager
          image: quay.io/backube/volsync:0.12.1@sha256:2dd1ef4251b3a5881ab9289dce481de3fe30da7fc8da5e4dfed2d562964c888a
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
            - --scc-name=volsync-privileged-mover
          command:
            - /manager
          env:
            - name: VOLSYNC_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELATED_IMAGE_RSYNC_CONTAINER
              value: quay.io/backube/volsync:latest
            - name: RELATED_IMAGE_RSYNC_TLS_CONTAINER
              value: quay.io/backube/volsync:latest
            - name: RELATED_IMAGE_RCLONE_CONTAINER
              value: quay.io/backube/volsync:latest
            - name: RELATED_IMAGE_RESTIC_CONTAINER
              value: quay.io/backube/volsync:latest
            - name: RELATED_IMAGE_SYNCTHING_CONTAINER
              value: quay.io/backube/volsync:latest
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tempdir
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: volsync-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - emptyDir:
            medium: Memory
          name: tempdir
