---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: volsync
namespace: volsync-system

resources:
  - https://github.com/backube/volsync//config/default/?ref=v0.9.1

patches:
  - path: securityContext.yaml
  - path: control-plane-nodeAffinity.yaml

images:
  - name: quay.io/backube/volsync
    newTag: 0.9.1
