---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: volsync-system

resources:
  - https://github.com/backube/volsync//config/default/?ref=v0.12.1

patches:
  - path: patch-security-context.yaml

images:
  - name: quay.io/backube/volsync
    newTag: 0.12.1@sha256:2dd1ef4251b3a5881ab9289dce481de3fe30da7fc8da5e4dfed2d562964c888a
