---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/backube/volsync//config/crd?ref=v0.12.1
  - clusterrole-volsync-manager.yaml
  - clusterrole-volsync-metrics-reader.yaml
  - clusterrole-volsync-proxy.yaml
  - clusterrolebinding-volsync-manager.yaml
  - clusterrolebinding-volsync-proxy.yaml
  - deployment-volsync-controller-manager.yaml
  - namespace-volsync-system.yaml
  - role-volsync-leader-election.yaml
  - rolebinding-volsync-leader-election.yaml
  - service-volsync-controller-manager-metrics.yaml
  - serviceaccount-volsync-controller-manager.yaml
