---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: volsync-system
  name: volsync-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: volsync-leader-election
subjects:
  - kind: ServiceAccount
    namespace: volsync-system
    name: volsync-controller-manager
