---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-server
data:
  local.conf: ""
  exports.conf: |
    EXPORT
    {
        Export_ID=1;
        Path = "/media";
        Pseudo = "/media";
        Access_Type = RW;
        FSAL {
            Name = VFS;
        }
    }
