---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: nfs-server
namespace: nfs-server

resources:
  - configmap.yaml
  - namespace.yaml
  - pvc-media.yaml
  - service.yaml
  - statefulset.yaml
