---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-oauth2-proxy.yaml
  - httproute-sillytavern.yaml
  - namespace-sillytavern.yaml
  - pvc-data.yaml
  - sealedsecret-oauth2-proxy.yaml
  - service-oauth2-proxy.yaml
  - service-sillytavern.yaml
  - statefulset-sillytavern.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: sillytavern
    app.kubernetes.io/instance: sillytavern
  disableNameSuffixHash: true

configMapGenerator:
  - namespace: sillytavern
    name: config
    files:
      - config/config.yaml
