---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: metallb
namespace: metallb-system

resources:
  - github.com/metallb/metallb/config/frr?ref=v0.14.5
  - ipaddresspool-default.yaml
  - l2advertisement-default.yaml

patches:
  - path: control-plane-nodeAffinity-patch.yaml
