---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: jdmarble.net
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - External Services:
      - Cloudflare:
        - href: https://dash.cloudflare.com
      - Backblaze:
        - href: https://secure.backblaze.com/b2_buckets.htm
    - Projects:
      - Happyfold:
        - href: https://github.com/jdmarble/happyfold
  services.yaml: |
    - System:
      - Authelia:
          href: https://auth.jdmarble.net/
          siteMonitor: https://auth.jdmarble.net/
          namespace: authelia
          app: authelia
          podSelector: ""
      - Longhorn:
          href: https://longhorn.jdmarble.net/
          siteMonitor: https://longhorn.jdmarble.net/
          namespace: longhorn-system
          app: longhorn
          podSelector: ""
      - UniFi:
          href: https://udm-pro.jdmarble.net/
          siteMonitor: https://udm-pro.jdmarble.net/

    - Media:
      - Jellyfin:
          href: https://jellyfin.jdmarble.net/
          siteMonitor: https://jellyfin.jdmarble.net/
          namespace: jellyfin
          app: jellyfin
          podSelector: ""

    - Other:
      - Mealie:
          href: https://mealie.jdmarble.net/
          siteMonitor: https://mealie.jdmarble.net/
          namespace: mealie
          app: mealie
          podSelector: ""
      - NetBox:
          href: https://netbox.jdmarble.net/
          siteMonitor: https://netbox.jdmarble.net/
          namespace: netbox
          app: netbox
          podSelector: ""
      - OctoPrint:
          href: http://octopi.jdmarble.net/
          siteMonitor: http://octopi.jdmarble.net/
          widget:
            type: octoprint
            url: http://octopi.jdmarble.net
            key: '{{HOMEPAGE_FILE_OCTOPRINT_API_KEY}}'
      - Pelican:
          href: https://pelican.jdmarble.net/
          siteMonitor: https://pelican.jdmarble.net/
          namespace: pelican
          app: pelican
          podSelector: ""
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: false
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

  docker.yaml: ""
