---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    checkov.io/skip1: |
      CKV_K8S_38=The service account token is necessary to query service status.
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:v1.1.1@sha256:be49a60307fcce7909acdaf2f3b2f3d168a0468d62869bf72d380625dde91fb9"
          imagePullPolicy: Always
          env:
            - name: HOMEPAGE_FILE_OCTOPRINT_API_KEY
              value: /app/secrets/octoprint-api-key
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.jdmarble.net
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
              scheme: HTTP
              httpHeaders:
                - name: host
                  value: localhost:3000
            initialDelaySeconds: 0
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
              scheme: HTTP
              httpHeaders:
                - name: host
                  value: localhost:3000
            initialDelaySeconds: 0
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 10m
              memory: 150M
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
            - mountPath: /app/secrets
              name: api-keys
      securityContext:
        fsGroup: 11912
        runAsNonRoot: true
        runAsUser: 11912
        runAsGroup: 11912
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: api-keys
          secret:
            secretName: api-keys
        - name: logs
          emptyDir: {}
