---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: homepage
  name: api-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: octoprint-api-key
      remoteRef:
        key: homepage_octoprint-api-key
