---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: homepage
namespace: homepage

resources:
  - ciliumnetworkpolicy-homepage.yaml
  - clusterrole.yaml
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - namespace.yaml
  - sealedsecret-api-keys.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
