---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: homepage
namespace: homepage

resources:
  - clusterrole-homepage.yaml
  - configmap-homepage.yaml
  - deployment-homepage.yaml
  - httproute-homepage.yaml
  - namespace-homepage.yaml
  - sealedsecret-api-keys.yaml
  - secret-homepage.yaml
  - service-homepage.yaml
  - serviceaccount-homepage.yaml
