---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: homepage
spec:
  encryptedData:
    octoprint_api_key: AgAHYJ1sVTQYDr67woxJWitJhpfQiWjOIVfeAdORN9PFWpl+8ptaa5qUFT8C1zfJ3m8DCidcW/qg0gqefyFNuBtWPBA8zlnetS7PEv7wNHI3e37epRE5O6j3R/IjFLCvyIINMpD9E4VutfFbBRTIBpXnFX6JblPhcas0ET5lRx+8FotmPmbawZvoy+ihG79ZeQaFDIkhoAtt+gDu0Skv3k9S/oLPA4Azq4PH/nsib5ooCrFYkhSQeVCsvql3wpW58gmYzirpoTylcMfC8wFI9DW/3DhmLwGXACFqmSIcczdRCW4DaTEvZ4lzPSSBiCudvY4BJo1D8Lpus6S3qOUTxyF1c7/u5tqADmYgObIaOh7S14HnLFumv/ovpg4jlFDXsSlSXT1lhqNkVlBTu57QbEIYUNXVFinsFMBM3z2vCb8VFVS99fRg4suVCMdqxs1TYgFXlEumyj/ujDyQ5aQ1TaVayA4OUO6q5q5/7tts+qzOix3YcYPgA6y5PsXSTwfkhjdAM01WdTzWJRIahQZC8/RFV6oCgX4T2cZxhlGdrIkWtmeIFzZ/VF3/W+gpMD7h+8g62ZuVnG7EF3UN8viGOMCZBib/mGGciTI3U4pK+HytN2RGCfnihJbBVJTQHCWIsyzsQvp+1ff+KI1SMIW3Fizi5dwTUjtnnYIqpQA0y/fxYZMnA5C331fXbj1Bv5pbgf3NoEeNTmsIHLGeVJquVvhPeBodOB530U8esI9mHzsLxw==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: homepage
