---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: homepage
spec:
  encryptedData:
    octoprint_api_key: AgAfWLAnjGbR+t0JVgD1IZJiiKsT5Se0VtMiwM5NjIV2BTbKJ8qqiVAjY66q6Oj2lhrIQrW49G0lFEqexczD0E+V3QIlUl0QIeqTIKW6kjcN93EzPGs6kqO/7kCD4IMv8uhXtntXD7fAOqbKwmWCQ+iZNSwNXljUXzafO9Z3aSPHO4P8SEkpMSbeEXEA723ePaQYfHOvqNrjjpk50RUBkv7TW6EoxtiQp9PFsQho2ftTCPEsgtZ53s+1jSOWfYnnbdKzul06guOfJywIgjrHuqCfdjQkiZ7LWNDWHm7GtN6fzP31ZI3dEZNtTrrk1EpgfOIpAYIWHX7zJNVPo8dXCVdkPwkCWZUn5ZXoqHswkrjpyGzBtrETcOk1VS16GAYTspDItxPgdpkuTljIesq2J+c/xf/2P62N6g0OC0XzP3mozQDFykLeHo+ria/1vqYddPwV6Ac3C/WD6q0woqb13v79OMgOeutWfKZBwJYs4QzHXjXTegUtML5fWZF7JCchakupX3pqlhT4IQFfmOGu6fCSsYryv6HH+dp+iEyTXM2kx1SAbUaEY8fFTpmjqcCkj0V+TOKQV//+X0o6r73TJMRUYxyRKJupZdkjgmLlnDhw5lrKSB2unog8hudXQ2kbZo8XJG7Pbxj6wkmc66AsVbjoi5szL+0/mbdgRbE2wbXN/IjoZK+rLedLLzG3A0dT3zu2YoSwMUOE2IlvZgJ5fw46BMaKg93b6S/K0SC5c67bscLTOyeseqgNqXiA
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: homepage
