---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: zomboid
  name: zomboid
  labels:
    app.kubernetes.io/instance: zomboid
    app.kubernetes.io/name: zomboid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: unsafe
