---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  namespace: zomboid
  name: zomboid
spec:
  sourcePVC: zomboid
  trigger:
    # Synchronize every day at 0354
    schedule: "54 3 * * *"
  rclone:
    rcloneConfig: rclone-source
    rcloneConfigSection: net-jdmarble-zomboid-RW
    rcloneDestPath: "net-jdmarble-zomboid"
    copyMethod: Clone
    moverSecurityContext:
      fsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
