---
apiVersion: v1
kind: Service
metadata:
  namespace: zomboid
  name: zomboid
  labels:
    app.kubernetes.io/instance: zomboid
    app.kubernetes.io/name: zomboid
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.129
  ports:
    - name: steam
      port: 16261
      protocol: UDP
      targetPort: steam
    - name: udpraknet
      port: 16262
      protocol: UDP
      targetPort: udpraknet
    - name: rcon
      port: 27015
      protocol: TCP
      targetPort: rcon
  selector:
    app.kubernetes.io/instance: zomboid
    app.kubernetes.io/name: zomboid
