---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: zomboid
  name: zomboid
  labels:
    app.kubernetes.io/instance: zomboid
    app.kubernetes.io/name: zomboid
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: zomboid
      app.kubernetes.io/name: zomboid
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: zomboid
        app.kubernetes.io/name: zomboid
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      containers:
        - name: zomboid
          image: docker.io/ipshosting/game-pz:v1@sha256:4927002c88a1bb0a9877994dc8946bf881285607bba9842c9ff9b30ac6655ad0
          envFrom:
            - configMapRef:
                name: config
          ports:
            - name: steam
              protocol: UDP
              containerPort: 16261
            - name: udpraknet
              protocol: UDP
              containerPort: 16262
            - name: rcon
              protocol: TCP
              containerPort: 27015
          resources:
            requests:
              memory: "8G"
              cpu: "1"
            limits:
              memory: "8G"
              cpu: "4"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: data
              mountPath: /home/ips-hosting
            - name: tmp
              mountPath: /tmp
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zomboid
        - name: tmp
          emptyDir: {}
