---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        args: ["--strict"]
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "3.2.394"
    hooks:
      - id: checkov
        name: Checkov apps/authelia
        files: ^apps/authelia/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/authelia"
      - id: checkov
        name: Checkov apps/cert-manager
        files: '^apps/cert-manager/.*\.yaml$'
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/cert-manager"
      - id: checkov
        name: Checkov apps/cloudnative-pg
        files: '^apps/cloudnative-pg/.*\.yaml$'
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/cloudnative-pg"
      - id: checkov
        name: Checkov apps/external-dns
        files: ^apps/external-dns/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/external-dns"
      - id: checkov
        name: Checkov apps/external-secrets
        files: ^apps/external-secrets/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/external-secrets"
      - id: checkov
        name: Checkov apps/external-snapshotter
        files: ^apps/external-snapshotter/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/external-snapshotter"
      - id: checkov
        name: Checkov apps/gateway
        files: ^apps/gateway/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/gateway"
      - id: checkov
        name: Checkov apps/homepage
        files: ^apps/homepage/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/homepage"
      - id: checkov
        name: Checkov apps/jellyfin
        files: ^apps/jellyfin/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/jellyfin"
      - id: checkov
        name: Checkov apps/kubelet-serving-cert-approver
        files: ^apps/kubelet-serving-cert-approver/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/kubelet-serving-cert-approver"
      - id: checkov
        name: Checkov apps/longhorn
        files: ^apps/longhorn/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/longhorn"
      - id: checkov
        name: Checkov apps/mariadb-operator
        files: ^apps/mariadb-operator/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/mariadb-operator"
      - id: checkov
        name: Checkov apps/mealie
        files: ^apps/mealie/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/mealie"
      - id: checkov
        name: Checkov apps/metrics-server
        files: ^apps/metrics-server/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/metrics-server"
      - id: checkov
        name: Checkov apps/netbox
        files: ^apps/netbox/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/netbox"
      - id: checkov
        name: Checkov apps/pelican
        files: ^apps/pelican/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/pelican"
      - id: checkov
        name: Checkov apps/volsync
        files: ^apps/volsync/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/volsync"
