---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: ["--strict"]
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "3.2.250"
    hooks:
      - id: checkov
        name: Checkov apps/argocd
        files: '^apps/argocd/.*\.yaml$'
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/argocd"
      - id: checkov
        name: Checkov apps/authelia
        files: ^apps/authelia/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/authelia"
      - id: checkov
        name: Checkov apps/external-dns
        files: ^apps/external-dns/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/external-dns"
      - id: checkov
        name: Checkov apps/homepage
        files: ^apps/homepage/.*\.yaml$
        entry: checkov
        args:
          - "--quiet"
          - "--framework=kustomize"
          - "--directory=apps/homepage"
