---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone-source-config
  namespace: jellyfin
spec:
  encryptedData:
    rclone.conf: AgCHv1methZ8llLV/HrPS8FjtAe586GGCbk80WKnjipA6SgX3wY55rbanF74z4TZ9gt2azloCSJD9wdbSukfv06jSZUlXe9CUZIcEUNVnhfLCILSfpTSpPZgoZXRNcIbVGkADfjIkYRd+DMCHPVWVmXHuoCOlLbLG+QImlchZzG/hDlA+8LyaDEpqaBVKwHvtHXWTuJ0PDwBkdCA3hyORzFKOAOHT9/JupY64w9UysK3FhDsZTnUSNyz5BAMQoLj9Ws4d96d2WTfpznExl4wmG2AM3tw9r39ETJ0YuKbdyzlC6sgDrFj7AQMCrGtG9PfxLipFXsRrXoUeNa6fhaLQ+pcy5Mcmy+ZzqWO+XncirPBJB5ALaQNht38vXik1Ncect3cJ/MbLP+upX6nel0Bcyerltnz/m69ayskC1XDTIG2BFtnHqqiHqzjs514ZyzhnAI6KBxmHZEsw1EGCoIoLv+9psFjXjf14lm0rwb8u/a7xL4aa/RwBW1/Mp2qZi+ZPgVQIcT83ZFd/hCqj8icTkdSmgehH0/6zJk48txfRimWOAR97Kb1C+LQU4FUGtH94nQgcd6JLpl2u6Tnf/G+6P765GWj4qLXiuu1uHHQyfZ08NwN8O2PWBzfY20vYc+Uvw/sqnXbEIyMNokBHScaGszME+vxfJ4nznXgeu/bxRNSBjOOfvGuG0twaZowqd58tA5K5GgspOiKZ9TQALtwL9LSJi0n456N+9zquAZ+rSRopCESQWzDjJ/+zDS+zTu7Mql8YoTEOId8BpWpeHG2OOQB0no40tODdmz0fMQIKFRRjEt7ZtQKDT0Aix6fYUzIKgjD/Ux3j3UbVRXFdGJBIhAYfDBSdSEK0Rj02Flp4gq+PWrbTQ==
  template:
    metadata:
      creationTimestamp: null
      name: rclone-source-config
      namespace: jellyfin
