---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: jellyfin
namespace: jellyfin

resources:
  - deployment.yaml
  - namespace.yaml
  - pvc-jellyfin-config.yaml
  - replicationdestination-jellyfin-config.yaml
  - replicationsource-jellyfin-config.yaml
  - sealedsecret-rclone-destination-config.yaml
  - sealedsecret-rclone-source-config.yaml
  - service.yaml
