---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-jellyfin.yaml
  - externalsecret-rclone-config.yaml
  - httproute-jellyfin.yaml
  - namespace-jellyfin.yaml
  - pvc-jellyfin-config.yaml
  - replicationdestination-jellyfin-config.yaml
  - replicationsource-jellyfin-config.yaml
  - service-jellyfin.yaml
