---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: jellyfin
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: jellyfin-config
  resources:
    requests:
      storage: 1Gi
  storageClassName: unsafe
