---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  namespace: jellyfin
  name: jellyfin-config
spec:
  sourcePVC: jellyfin-config
  trigger:
    # Synchronize every day at 0123 hours
    schedule: "23 1 * * *"
  rclone:
    rcloneConfig: rclone-config
    rcloneConfigSection: net-jdmarble-jellyfin
    rcloneDestPath: "net-jdmarble-jellyfin"
    copyMethod: Clone
