---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  namespace: jellyfin
  name: jellyfin-config
spec:
  rclone:
    accessModes:
      - ReadWriteOnce
    capacity: 10Gi
    copyMethod: Snapshot
    storageClassName: unsafe
    volumeSnapshotClassName: longhorn
    rcloneConfig: rclone-config
    rcloneConfigSection: net-jdmarble-jellyfin
    rcloneDestPath: "net-jdmarble-jellyfin"
  trigger:
    manual: restore-once
