---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone-source-config
  namespace: jellyfin
spec:
  encryptedData:
    rclone.conf: AgCdUVw+yro8S1Tp6ijbpYLy4BKOoB/PxXs5xVWu5nlwAipIFOAQRpBcizoCAzD7eq+4Ck4v5srAfZsByeSVbEzDo32G91CjXq5KSaHurAwiy6NjJ0gs0mdlpbuYLM7wmS9TnrGpMYlU57oHj9yPCFf3tcZp/vUQKsNiElLoj01Lh97HcF/DPWG0iYYdLMvulaGmx3NdsMJILjAwE8mwUg3J2znxNYprx4tFVOnFXQQFTMdmrISfSFsHQ7kUk0Jd01TBt/LZi73MQNrSm4U4RaAQ7QyZ1m69T6JRosk4ULd1qwqEQHcCS045hphygsNsNxg4xkyLeIetEJCppKNG3LUhAmRiizOQoUyoIxIm0QO4UdYkg3XSPv0gAMg3nOL0gvbTUGRSQgtgq0hGI1eBLgdeMRP951jJvwgdoomeGFZwKlEnZwzju7LQt2WDWaUs31AzzJgnySO7JRX/FNhAzo5TMAegui5Yh1vBjYKmieNkz7D2kV9rGID3XNM+yD9PDsJVAHa9M1sBs2Kab6VOEyM8EMCZsc2jXEY5rFhSqQkR4Tjw9IWAt5I+B2JMXXsnbdhsdSFGLELsu3y0ZM5g/3Gxrii7uHGBgcpsl+e8K4IC7o1peZpsSMf/mld8P9UpvFzFZBqEr+ltmiLPQnBi3POuv/Yw6bk0z7r1o06+n1c0WqeKfB4UqDWIX/jzMQPRCm+xs3QZ2jNBRb3+1WONnnT4PH0n4ust8lwe9jUpdXUHjPHE5Ctctwtx1pqG6hvCTQeCVr6gyf5G8lhpvSnMhYIEk8z0MDUcp+AyivCk8PcdhpP1XsaMkQn94DFYXmhAuNZiv1LbZHNq38skVUdlRA6eQ26lPQnPwKEFSsvfPlzL+Ke9Yg==
  template:
    metadata:
      creationTimestamp: null
      name: rclone-source-config
      namespace: jellyfin
