---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  namespace: external-secrets
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-machine-client
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-machine-client
      secretsScope:
        projectSlug: jdmarble-net
        environmentSlug: prod
        secretsPath: /
        recursive: true
