---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

resources:
  - clustersecretstore-infisical.yaml
  - namespace-external-secrets.yaml

helmCharts:
  - repo: https://charts.external-secrets.io
    name: external-secrets
    version: v0.14.4
    releaseName: external-secrets
    namespace: external-secrets
    valuesFile: values.yaml
    skipTests: true
