---
webhook:
  lookaheadInterval: 48h
  certManager:
    enabled: true
    cert:
      issuerRef:
        kind: ClusterIssuer
        name: ca
      revisionHistoryLimit: "2"
      duration: 168h  # 1 week
      renewBefore: 72h
