apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.releases.teleport.dev
    chart: teleport-kube-agent
    targetRevision: 14.0.0
    helm:
      values: |
        proxyAddr: teleport.jdmarble.net:443
        kubeClusterName: jdmarble.net
        joinTokenSecret:
          create: false
        roles: app,discovery
        kubernetesDiscovery:
          - types: ["app"]
            labels:
              teleport.jdmarble.net: expose
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-kube-agent