apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.releases.teleport.dev
    chart: teleport-kube-agent
    targetRevision: 13.3.8
    helm:
      values: |
        kubeClusterName: jdmarble.net
        proxyAddr: teleport.jdmarble.net:443
        joinTokenSecret:
          create: false
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-kube-agent