---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-letsencrypt-cloudflare-dns
spec:
  acme:
    email: jdmarble@jdmarble.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: apiKey
