---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: authelia
  name: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
      remoteRef:
        key: authelia_password-reset-jwt-secret
    - secretKey: AUTHELIA_SESSION_SECRET_FILE
      remoteRef:
        key: authelia_session-secret
    - secretKey: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
      remoteRef:
        key: authelia_storage-encryption-key
    - secretKey: jwks.rsa.2048.key
      remoteRef:
        key: authelia_jwks-key
