---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authelia
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: authelia
      app.kubernetes.io/name: authelia

resources:
  - httproute-authelia.yaml
  - namespace-authelia.yaml
  - sealedsecret-authelia.yaml
  - service-authelia.yaml
  - statefulset-authelia.yaml

configMapGenerator:
  - name: authelia
    files:
      - configs/configuration.yaml
      - configs/users.yaml
generatorOptions:
  disableNameSuffixHash: true
