apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: 9.4.0
    helm:
      values: |
        redis-cluster:
          enabled: false
        postgresql:
          enabled: false
        postgresql-ha:
          enabled: false

        persistence:
          size: 50Gi
          storageClass: local-path
        service:
          http:
            clusterIP:
            annotations:
              teleport.jdmarble.net: expose
              teleport.dev/protocol: http
              teleport.dev/name: gitea
              teleport.dev/public-addr: "gitea.jdmarble.net"
              teleport.dev/labels: |
                purpose: devtool
              teleport.dev/app-rewrite: |
                headers:
                  - "X-Webauth-User: {{internal.logins}}"
                
        # Can't use RollingUpdate with local database because the old pod holds a DB lock. 
        strategy:
          type: Recreate
        gitea:
          config:
            cache:
              ADAPTER: memory
            database:
              DB_TYPE: sqlite3
            queue:
              TYPE: level
            repository:
              ENABLE_PUSH_CREATE_USER: true
              ENABLE_PUSH_CREATE_ORG: true
            security:
              REVERSE_PROXY_TRUSTED_PROXIES: "*"
            server:
              DOMAIN: gitea.jdmarble.net
              ROOT_URL: "https://gitea.jdmarble.net/"
              LFS_START_SERVER: true
            service:
              ENABLE_REVERSE_PROXY_AUTHENTICATION: true
              ENABLE_REVERSE_PROXY_AUTO_REGISTRATION: true
            session:
              PROVIDER: memory

  destination:
    server: https://kubernetes.default.svc
    namespace: gitea