# Configure Longhorn not to use the Talos system disk for storage.
# Instead, only use the disk mounted at /var/mnt/local
# and only if the node is labeled as having a default disk.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    create-default-disk-labeled-nodes: true
    default-data-path: /var/mnt/local
    priority-class: longhorn-critical
    storage-reserved-percentage-for-default-disk: 0
    taint-toleration: "node-role.kubernetes.io/control-plane:NoSchedule"
