---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: longhorn-system
  name: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: client_secret
      remoteRef:
        key: longhorn_oidc-client-secret
    - secretKey: cookie_secret
      remoteRef:
        key: longhorn_cookie-secret
  target:
    template:
      data:
        oauth2-proxy.conf: |
          client_secret = {{ .client_secret }}
          cookie_secret = {{ .cookie_secret }}
