---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.8.0/deploy/longhorn.yaml
  - deployment-oauth2-proxy.yaml
  - externalsecret-oauth2-proxy.yaml
  - httproute-ui.yaml
  - service-oauth2-proxy.yaml
  - storageclass-safe.yaml
  - storageclass-unsafe.yaml
  - volumesnapshotclass-longhorn.yaml

patches:
  - path: patch-default-setting.yaml
  - path: patch-privileged-pod-security.yaml
  - path: patch-single-replica-ui.yaml
