---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy
  namespace: longhorn-system
spec:
  encryptedData:
    oauth2-proxy.conf: AgChwnO14zxc5r9C22F/4lGLStUsw0akybuaYCbZu65PhRBMSfmWmYNOSHen1pxObs6AKaLBZvrAqjLfKKml6QI1AlQ8LE5N6+LRhSNwA+CEKu951sqtKncRY4VqcYY1qVzSemrcRz4AYAP8FsRQcI902xSRfanh0H2Q2dkNR3HhjYLUd9lfLjyqBxWKmcL/jHugIzhICqOdu1hJvBuU/PHeWo6SGp7ih5ncz8TZ6L7z4Vo85/xEj5wQHyCkEnCoFhHle4sRsjN/+fePxnxJyrJ5F05dGihGpb2/sPgrG7kC951xoGuDJGAVLwvppL7AhvHB4TG000CzNe0sESQNn6djtTfcDTXT6QrxXnfsjmHQ9aUcLxly0NbeNjFpPIHifXuFNY13pgo6P5fZd1a6i86v2Ie0Wx1HntwCE7KjlQg0ghaCtYuxORQz5M6YiaIEVZ0n6yQsa6z4WqgcR6exTDkJ9D8TNXjCibguEv2rGmyRcc1AV297MRbkZUSoeEHi9BGcFXvYXsu10rsvY73A1yOqXMcIXlY85YSwRj1CoW76ZhhPaIaB6fcYUeyA7+p4WirtJfSE3IjQ0EHrdJBj6rUdwjWbPlSJ+xX7kRxKlGYcWGDlp2yiRfnbm5WvRK57cGRcKekoIr0MWJekLYeTpDId/S2xGjRyYszvqgcN5o3Vhyu/Q+O3Rhop9qkKrq3Fptw6rofTtOIIA/RvTy+0/tSnpkcuV4EUXaayuGbROYjokxjZT6IaiQTH+kmb86p8mnidK2h+jYcTV42Q+94+cKnOEHsPwsBB8JsgsGkkF7r5Z+jDGP5fu+nxAErFzuFKh9NSOTLZTbVgBslxgdaZxBQhkMqMLkA4gQqnJI/IMP7KnQ==
  template:
    metadata:
      creationTimestamp: null
      name: oauth2-proxy
      namespace: longhorn-system
