---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy
  namespace: longhorn-system
spec:
  encryptedData:
    oauth2-proxy.conf: AgB8iNlCvr1ebWUGYLAKVHtCwbjBk6rG+TWq8Rj8ebqWFgxSIJk8BMLTHrNcdFAjg4CDDYqhd5E6Hbk8fAr+nPk9+fyRR7RwgW53G78/D8RLPc6SYLtVJpVhzb128Xxu/CXAbrlCnakQbNiy2WchX5IHCkd5lP3eM8/cdnwY6y1ZdhvhsqTSuDc/EgOa+o6PuLxUpzsxrMDjqJO+90kAmQTZKpEh7/NHIA8aaSWjF/25snMAKkv7SWFW74kxhznpzW9+wqIXd4HegttkXk+zVmuZlxln20URzgeoIcTGdoaQqK3TgOXjj19quvIRtrhnWMSIkPWeXls63BbvTXlJhQl250aul6kGBCccroOYeFpuPVN38aJQx9c12GBWncZWJHGZOGNHlaENslHKWBBB49nU2hXZzoIzzKA/Vp48hokSJcXrXWFk5RMjs79x5zBTkbWtfnwQNEzUn8QtjodnPsodVIXED922ZHX4JVG/YDhmy6EB6BcdtUocbtX8VofL0IV+YHY8exD5mmqr9BH/h4dObUNppfB7B7losX+FiLcHd1F8Y+Fl1/z1HneaYKidgPV6QlWQ2PTDoY3zFy9fdfrnD0fjDbsxbjQKH9nKxPW1cMVE/Wj31KQksMwO1YsGZtDmka94zPwb5FuQZ6DRG1GTLlStnC0F9lI+dt971AtNVfRyuLTfLTjdgjpKRicQw5QBzHXWQyJCXln8WwAYUadTnoG35sEUMapS7XdwTybJYXsg91LHjRjiIrmbk1XOKwpBGlwk/tIZ2RH3nxSJGsylSugGxoT5R5SkVuB07QgWJ1ZvaOU6TjK25UPPdKxwBWwebf1JvHIQOALjq4aw/EN0qpbSo2W5z+nu8EgD29Bdqsbei7RDYD/nf1ovVyNKp1DpYiA70F+C48YZLnaUf/1t8oK/SppUCUlO7lu82Dj/Fvz9LJoQo7jpX2DZmEBiTgP9QDOAO8msa/LRlbSNopCVgg==
  template:
    metadata:
      creationTimestamp: null
      name: oauth2-proxy
      namespace: longhorn-system
