---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy
  namespace: longhorn-system
spec:
  encryptedData:
    oauth2-proxy.conf: AgCRd5MlpsLRW4p5XEbNPr0/8OyigMat6uwJ1uVnN9jfRof5jsXhQ0MeYmN+V/OQSYNDyNHdc5aBU0JFThKD6umPXrDXHPUQjnnLnAAprZXUSQBTIagBNAD0Oy6KH2O52ZBndVsK5m5+/QATKnyf9sX6hJGetELObl8p/WoyAKAZScLzAmJB0AI3fCJXGvDgGtOiLqueyuDaCu8XQD7stBo6kerUPF9+06IbLUmhVP7B8P5fWDGm5MX3FWO4HUo3y7dRsRXI4VActQXcaGqMq2iZezwIhnzKHD26GnR0fnDvAFSv3FbtpaNCjn3xLPf+uRHAk3XwCgqmB4xfONMQJgh9rK5iARyAiU2U8YR3LrtTYN4Fk95EJgrbDDa2eFXyFHy9qzm5HengYC/lhf7bKwflXKkHOLGiEiJK4875m2SNoj/3l9cG3sCbAAgmfOL8ShVO8vbcAMTTJFUKSU2zk4UArXZ8H+SWl61p5IVZi4FVpO4RQfnGAUqAzp0AxCXW5tZMyt+CN+CeEdkm4+sqCqTgf4l4nzWaMuQQeoRfZhMIoUCHd/xwt4zugTebxRUPoj8i231iifDAxrplQ/65DNATrdGyUThpCIRGGNPXLaPOfOcKYtwQ0iNTohHAebpw/Vy7cM7GEkSt8nUMhuysTSwWps3tHsNUNI5FyB5gaiKS93dpfH9ox6T8qNX11wj7IOj3GoJ8ErZPBM3YCtMrlzNw38QOI/qbIoeNoOcGWng69Eyh4UokLIQ5dCTq9bQZ1/K2oK4wR7FQlkFig4dtMrPMhZ1pIrf0qFBl5FTsdtIl/jJxKezHkqZsQrPDsWOhnFwPsp762loPfqrsJbhuKVYi6AEf0QS9b2r7igy9hRDRiFiS2NA+t3YGVZkCv39J2LvMrNhDOjqX/a1JUpASJ5AFa3vY1g2LRV9aYwgtkpt9F9jz0kjvBPqLlptL7keQbl0tc5V/bCgKut33+Bua74wRtw==
  template:
    metadata:
      creationTimestamp: null
      name: oauth2-proxy
      namespace: longhorn-system
