# I don't need an HA web UI.
# I configure Longhorn declaratively and use the UI for sanity checks.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  replicas: 1
