---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: unsafe
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  unmapMarkSnapChainRemoved: "ignored"
