---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

resources:
  - namespace-sealed-secrets.yaml
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.28.0/controller.yaml

images:
  - name: docker.io/bitnami/sealed-secrets-controller
    newName: ghcr.io/bitnami-labs/sealed-secrets-controller
    newTag: 0.28.0@sha256:5b6123f258131aaa0c184daec514e582f28c291a84ad723a8caa3a8b39374c96

patches:
  - path: patch-checkov.yaml
