---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: sealed-secrets
namespace: kube-system

resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.27.0/controller.yaml

patches:
  - path: control-plane-nodeAffinity.yaml
