---
dataRoot: ./data
cardsCacheCapacity: 100
listen: false
protocol:
  ipv4: true
  ipv6: false
dnsPreferIPv6: false
autorunHostname: auto
port: 8000
autorunPortOverride: -1
whitelistMode: false
basicAuthMode: false
basicAuthUser:
  username: user
  password: password
enableCorsProxy: false
requestProxy:
  enabled: false
enableUserAccounts: false
enableDiscreetLogin: false
autheliaAuth: true
perUserBasicAuth: false
sessionTimeout: 86400
# There's no where else the app will read this from and I don't want to make the entire config file a secret.
cookieSecret: DqD1W/FtQtHeGRdoo1+iae/qj1sWRXQqLHp90qpY/meY7Ifk1fXuTVJm70363QjwARG1eENXBkiafyce7Pb2wA==
disableCsrfProtection: false
securityOverride: true
autorun: false
avoidLocalhost: false
disableThumbnails: false
thumbnailsQuality: 95
avatarThumbnailsPng: false
allowKeysExposure: false
skipContentCheck: true
disableChatBackup: true
numberOfBackups: 50
maxTotalChatBackups: -1
chatBackupThrottleInterval: 10000
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
requestOverrides: []
enableExtensions: true
enableExtensionsAutoUpdate: true
enableDownloadableTokenizers: true
extras:
  disableAutoDownload: false
  classificationModel: Cohee/distilbert-base-uncased-go-emotions-onnx
  captioningModel: Xenova/vit-gpt2-image-captioning
  embeddingModel: Cohee/jina-embeddings-v2-base-en
  speechToTextModel: Xenova/whisper-small
  textToSpeechModel: Xenova/speecht5_tts
promptPlaceholder: "[Start a new chat]"
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
mistral:
  enablePrefix: false
ollama:
  keepAlive: -1
claude:
  enableSystemPromptCache: false
  cachingAtDepth: -1
enableServerPlugins: false
