---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Using the version recommended by Longhorn documentation.
  # https://longhorn.io/docs/1.8.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/#if-your-kubernetes-distribution-does-not-bundle-the-snapshot-controller
  - https://github.com/kubernetes-csi/external-snapshotter//client/config/crd/?ref=v8.2.0
  - https://github.com/kubernetes-csi/external-snapshotter//deploy/kubernetes/snapshot-controller/?ref=v8.2.0

patches:
  - path: hostname-podAntiAffinity.yaml
