apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: secrets-operator
    targetRevision: 0.2.1
    helm:
      releaseName: infisical
      parameters:
        - name: controllerManager.manager.image.tag
          value: v0.3.0
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical