---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kanidm-data
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: kanidm-data
  resources:
    requests:
      storage: 1Gi
  storageClassName: unsafe
