---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: kanidm-data
spec:
  sourcePVC: kanidm-data
  trigger:
    # Synchronize every day at 0155 hours
    schedule: "55 1 * * *"
  rclone:
    rcloneConfig: rclone-source-config
    rcloneConfigSection: net-jdmarble-kanidm-RW
    rcloneDestPath: "net-jdmarble-kanidm"
    copyMethod: Clone
    moverSecurityContext:
      fsGroup: 1911
      runAsNonRoot: true
      runAsUser: 1911
      runAsGroup: 1911
      seccompProfile:
        type: RuntimeDefault
