---
apiVersion: v1
kind: Service
metadata:
  name: kanidm
  labels:
    app.kubernetes.io/name: kanidm
  annotations:
    external-dns.alpha.kubernetes.io/hostname: idm.jdmarble.net
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    app.kubernetes.io/name: kanidm
