---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kanidm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kanidm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kanidm
    spec:
      securityContext:
        fsGroup: 1911
        runAsNonRoot: true
        runAsUser: 1911
        runAsGroup: 1911
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kanidm
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          image: docker.io/kanidm/server:1.3.3
          imagePullPolicy: Always
          volumeMounts:
            - name: "config"
              mountPath: "/data/server.toml"
              subPath: "server.toml"
            - name: "data"
              mountPath: "/data"
            - name: "db"
              mountPath: "/db"
            - name: "certs"
              mountPath: "/ssl"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
      volumes:
        - name: config
          configMap:
            name: kanidm
        - name: certs
          secret:
            secretName: idm-jdmarble-net-tls
        - name: "data"
          emptyDir:
            sizeLimit: 16Mi
        - name: db
          persistentVolumeClaim:
            claimName: kanidm-data
