---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb-operator

resources:
  - https://raw.githubusercontent.com/mariadb-operator/mariadb-operator/refs/tags/v0.37.1/deploy/crds/crds.yaml
  - namespace-mariadb-operator.yaml

helmCharts:
  - repo: https://helm.mariadb.com/mariadb-operator
    name: mariadb-operator
    version: 0.37.1
    releaseName: mariadb-operator
    namespace: mariadb-operator
    skipTests: true
    valuesFile: values.yaml
