---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: cert-manager
  name: cloudflare-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: apiKey
      remoteRef:
        key: external-dns_cloudflare-api-key
