---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: external-dns
namespace: external-dns

resources:
  - https://github.com/kubernetes-sigs/external-dns//kustomize/?ref=v0.14.2
  - namespace.yaml
  - sealedsecret-cloudflare-api-key.yaml

patches:
  - path: cloudflare-patch.yaml
  - path: securityContext-patch.yaml
