---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: external-dns

namespace: external-dns

resources:
  - https://github.com/kubernetes-sigs/external-dns//kustomize/?ref=v0.15.1
  - namespace.yaml
  - networkpolicy-external-dns.yaml
  - sealedsecret-cloudflare-api-key.yaml

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.15.1

patches:
  - path: patch-cloudflare.yaml
  - path: patch-gatewayapi-clusterrole.yaml
  - path: patch-probes.yaml
  - path: patch-resources.yaml
  - path: patch-securityContext.yaml
