---
apiVersion: v1
kind: Service
metadata:
  namespace: jellyfin
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.129
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http

  selector:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
