---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: nfs-server
namespace: nfs-server

resources:
  - configmap.yaml
  - namespace.yaml
  - pvc-media-movies.yaml
  - service.yaml
  - service-headless.yaml
  - statefulset.yaml
