---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  labels:
    app.kubernetes.io/name: mealie
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mealie
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v1.12.0
          imagePullPolicy: Always
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: TZ
              value: "America/Los_Angeles"
            - name: MAX_WORKER
              value: "1"
            - name: WEB_CONCURRENCY
              value: "1"
            - name: BASE_URL
              value: "https://mealie.jdmarble.net"
            - name: OIDC_AUTH_ENABLED
              value: "True"
            - name: OIDC_SIGNUP_ENABLED
              value: "True"
            - name: OIDC_CONFIGURATION_URL
              value: "https://auth.jdmarble.net/.well-known/openid-configuration"
            - name: OIDC_CLIENT_ID
              value: "mealie"
            - name: OIDC_AUTO_REDIRECT
              value: "false"
            - name: OIDC_REMEMBER_ME
              value: "True"
            - name: OIDC_ADMIN_GROUP
              value: admins
            - name: OIDC_USER_GROUP
              value: users
            - name: "DEFAULT_GROUP"
              value: "Bertini"
          envFrom:
            - secretRef:
                name: openai
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          volumeMounts:
            - mountPath: /app/data
              name: data
      securityContext:
        fsGroup: 911
        runAsNonRoot: true
        runAsUser: 911
        runAsGroup: 911
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mealie
