---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: mealie
  name: openai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: mealie_openai-api-key
