---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: mealie
  name: oidc-client
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: mealie_oidc-client-secret
