---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: mealie
      app.kubernetes.io/name: mealie
namespace: mealie

resources:
  - deployment.yaml
  - httproute.yaml
  - namespace.yaml
  - pvc.yaml
  - sealedsecret-openai.yaml
  - service.yaml
