---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-mealie.yaml
  - httproute-mealie.yaml
  - namespace-mealie.yaml
  - pvc-mealie.yaml
  - replicationdestination-mealie.yaml
  - replicationsource-mealie.yaml
  - sealedsecret-oidc-client.yaml
  - sealedsecret-openai.yaml
  - sealedsecret-rclone-destination-config.yaml
  - sealedsecret-rclone-source-config.yaml
  - service-mealie.yaml
