---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  namespace: mealie
  name: mealie
spec:
  rclone:
    accessModes:
      - ReadWriteOnce
    capacity: 1Gi
    copyMethod: Snapshot
    storageClassName: unsafe
    volumeSnapshotClassName: longhorn
    rcloneConfig: rclone-config
    rcloneConfigSection: net-jdmarble-mealie
    rcloneDestPath: "net-jdmarble-mealie"
    moverSecurityContext:
      fsGroup: 911
      runAsNonRoot: true
      runAsUser: 911
      runAsGroup: 911
      seccompProfile:
        type: RuntimeDefault
  trigger:
    manual: restore-once
