---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone-source-config
  namespace: mealie
spec:
  encryptedData:
    rclone.conf: AgAPN1Ka0T3PMr6mJml/M4WZZy6Cn00beOIg1+nYJOX4ij8eE5F7kjvkW2rAnoXY+zZcJPz+sWP4jay+JoKqfp7+O5jni2CKmAGjmj1SjJPXovE8oxZJRmqMLIdA9ATLOJ7EU/m/LXjLCwK1NSqlNNHV+7GPMp64iw77md9Y54rXptw2EtO8t0l4G5bSl9iPVQg30loQSjQBmDGY4Bzqwtf+vnPJNfWIiqP3WItbKt2UaYZuJmUBIk458A9BC0Fvi3hAdbulrkqTeqOwFTihBh7bxzRjKT4RtfTXGpiUMtUpXSUQ7g9kF85cpK52Ai96E7Z2xxbemCEEkE/7Ky9ckeYIQQ7ce17wkzHme+gwgM+/mUCMzk8RYmjrjv4zjhYbynQRtmeXKP2mR3s8QCb70Lhp9ErMFNdlRmzfT9N5F1mD6LjgStPfGYYOZYRF4mEWsM/vlivi5wYgKQNx34Vj9vO0yQJUhBRbH6hLnuoBz9mS/89ukNgyiAX7GgZFgv2+kTaX6Bwf9nIbiRzSOJRjmguSHvaZ6Zp2JRHuK85fjFJd2bBVP4CZxfPXO2B7/WeDq2sxu07rQo7X2PMP/TBWnACOZw80Z1kw5wsmMqDX4tVq0ANRAUaKYsvjbrzUWdIONGN1sak1UPe9oHuXAaqc8AfiIiOaqSb2eO0iPz7wcvAU6PQwjk3/bVEnrKLKfnDQs8+lGYe599HYw1lvVEZxmzzK2/vhQ/dZs4XgCyi4nwwAGH8Uyh0h1wzfYifoNTU0f+CVhxVn6C129pRLtqroVFct//jjD/RaCjOn2wvbD3r+UL7tLj4mmieRJQeWlLxVAORRNcwpsuo6bM27tcH+kq85eJ3aCQaJoKBl+in8NUPZmLI=
  template:
    metadata:
      creationTimestamp: null
      name: rclone-source-config
      namespace: mealie
