---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone-destination-config
  namespace: mealie
spec:
  encryptedData:
    rclone.conf: AgDOj7zYXp0QiPtBvzleZJNiMXl3FWcgsw6gj8RwH0KjZ75y5wxDTmNuc33pLvC91jgzQv4VUTkeylxCLodQvz4IBLlG4tJETW2zn3S27s8fiyXzaYcqVi7yFrTzbarT3SgS0tI6CauZXfz1Dm6X3MkunW4x058n4wzR3xwDp9QMHyWUtUCUQpoFrbI9v+LSLTI5Whd4+mx3sX4cSBMcEgvR0W2EGiuCX2NQRSdk9PVCFsDC3GtopI6rPMbkw91nbocsDvXz4gCfOznGKRFiazaI2JbSAS1fILCKqU4gnIrUC+s6lr2DzKOxfqLvpCbXJH+l9YAUCyOcIThl4W5o0H5B53AjAKuaLvd/m4VADjKeZ9plEOOvn3C13AsPGSVDhp7PyFhPG+fQrl2ZS0YUXuzibDKMGyYlXPGo2VENQIhPjAV8P9t9SC+d8pwnD3uooSUM/C7z+nqCvnIcOs8m8e+w6FiFA5fe6tc7V5RNIrnDLsh/6CowLwajzFYffy00WQaIYbFREOZDCcTfDQojuNmfPjqzUMu+bkcrmHdbGY3N07POeAZlvEfujFcCu9rAUgZa4nTvYYopvZEk3LQax9J/C1QHRCP8E0MTpfSmGzLL3AnbYHJJqKMAlECMve2uPkowTgYY4V7dsrbowj+kjjJXjaZMeAaUCQ0uMxfJ1/kp7t17/8nI5Ox8P/1eAqwwi/OApKs/vILaSSKo4IMTbxIobXTwisKfg5kA094ehUN/5Bb+sb6h4C9wjEgE8Wxq32Y1nqcLn6j3Ve2+8l+ztynQgu1mQkWHgR+U3pWsxWkXl1JOZlhBIFEIGrdprkpHxOA99v6UNprfy3YzSSGC5Q==
  template:
    metadata:
      creationTimestamp: null
      name: rclone-destination-config
      namespace: mealie
