---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: metrics-server
namespace: kube-system

resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.2/components.yaml

patches:
  - path: control-plane-nodeAffinity.yaml
