---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: jdmarble-net
  namespace: nginx-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare-dns
spec:
  gatewayClassName: nginx
  listeners:
    - name: https
      hostname: "*.jdmarble.net"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: jdmarble-net-tls
