---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: nginx-gateway
namespace: nginx-gateway

resources:
  - https://github.com/nginxinc/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v1.4.0
  - https://raw.githubusercontent.com/nginxinc/nginx-gateway-fabric/v1.4.0/deploy/crds.yaml
  - https://raw.githubusercontent.com/nginxinc/nginx-gateway-fabric/v1.4.0/deploy/default/deploy.yaml
  - gateway-jdmarble-net.yaml

patches:
  - path: privileged-pod-security-patch.yaml
  # Disable telemetry
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --product-telemetry-disable
    target:
      kind: Deployment
      namespace: nginx-gateway
      name: nginx-gateway
