---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: nginx-gateway
namespace: nginx-gateway

resources:
  - https://github.com/nginxinc/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v1.3.0
  - https://raw.githubusercontent.com/nginxinc/nginx-gateway-fabric/v1.3.0/deploy/crds.yaml
  - https://github.com/nginxinc/nginx-gateway-fabric/releases/download/v1.3.0/nginx-gateway.yaml
  - gateway-jdmarble-net.yaml
  - letsencrypt-cloudflare-dns-issuer.yaml
  - sealedsecret-cloudflare-api-key.yaml
  - service-nginx-gateway.yaml

patches:
  - path: privileged-pod-security-patch.yaml
