---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  annotations:
    external-dns.alpha.kubernetes.io/hostname: transmission.jdmarble.net
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: torrent-client
  type: LoadBalancer
