---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: mealie
  app.kubernetes.io/instance: mealie
namespace: mealie

resources:
  - deployment.yaml
  - namespace.yaml
  - pvc.yaml
  - sealedsecret-openai.yaml
  - service.yaml
