---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mealie
  labels:
    app.kubernetes.io/name: mealie
spec:
  storageClassName: unsafe
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
