---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: netbox
  name: oidc-client
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: SOCIAL_AUTH_OIDC_SECRET
      remoteRef:
        key: netbox_oidc-client-secret
