---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: netbox
  name: s3-backup-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: netbox_b2-account
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: netbox_b2-key
