---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: netbox
  name: netbox-redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: redis-password
      remoteRef:
        key: netbox_redis
