---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: netbox
  name: superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: api_token
      remoteRef:
        key: netbox_superuser-apitoken
    - secretKey: password
      remoteRef:
        key: netbox_superuser-password
  target:
    template:
      data:
        api_token: "{{ .api_token }}"
        email: jdmarble@jdmarble.com
        password: "{{ .password }}"
        username: jdmarble_admin
