---
superuser:
  existingSecret: superuser

persistence:
  # Disabling persistence to avoid [pitfalls](https://artifacthub.io/packages/helm/netbox/netbox#production-usage)
  enabled: false

timeZone: America/Los_Angeles

redis:
  enabled: false
cachingRedis:
  password: password
  existingSecretName: netbox-redis
tasksRedis:
  password: password
  existingSecretName: netbox-redis

postgresql:
  # Creating our own DB
  enabled: false

externalDatabase:
  host: pg-database-rw
  database: app
  username: app
  existingSecretName: pg-database-app
  existingSecretKey: password

allowedHosts:
  - "netbox.jdmarble.net"

remoteAuth:
  enabled: true
  backends:
    - social_core.backends.open_id_connect.OpenIdConnectAuth
  autoCreateUser: true

extraConfig:
  - secret:
      secretName: oidc-client
  - values:
      SOCIAL_AUTH_PIPELINE:
        [
          "social_core.pipeline.social_auth.social_details",
          "social_core.pipeline.social_auth.social_uid",
          "social_core.pipeline.social_auth.social_user",
          "social_core.pipeline.user.get_username",
          "social_core.pipeline.social_auth.associate_by_email",
          "social_core.pipeline.user.create_user",
          "social_core.pipeline.social_auth.associate_user",
          "netbox.authentication.user_default_groups_handler",
          "social_core.pipeline.social_auth.load_extra_data",
          "social_core.pipeline.user.user_details",
        ]
      SOCIAL_AUTH_OIDC_KEY: "netbox"
      SOCIAL_AUTH_OIDC_OIDC_ENDPOINT: "https://auth.jdmarble.net/"
      SOCIAL_AUTH_OIDC_SCOPE: ['groups']
