---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: gateway
  name: cloudflare-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: apiKey
      remoteRef:
        key: gateway_cloudflare-api-key
