---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  source:
    repoURL: https://github.com/jdmarble/happyfold.git
    targetRevision: HEAD
    path: deployments/external-dns/base
