---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: argocd
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.9/manifests/core-install.yaml
  - argocd-application.yaml
  - external-snapshotter-application.yaml
  - kubelet-serving-cert-approver-application.yaml
  - longhorn-application.yaml
  - metallb-application.yaml
  - sealed-secrets-application.yaml
  - volsync-application.yaml

patches:
  - path: control-plane-toleration-deployment-patch.yaml
    target:
      kind: Deployment
  - path: control-plane-toleration-statefulset-patch.yaml
