---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: volsync-system
  source:
    repoURL: https://github.com/jdmarble/happyfold.git
    targetRevision: HEAD
    path: deployments/volsync/base
