---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: factorio
  name: config
  labels:
    app.kubernetes.io/instance: factorio
data:
  server-settings.json: |
    {
      "afk_autokick_interval":0,
      "allow_commands":"admins-only",
      "auto_pause":true,
      "auto_pause_when_players_connect":false,
      "autosave_interval":10,
      "autosave_only_on_server":true,
      "autosave_slots":5,
      "description":"Marble Factorio Server",
      "ignore_player_limit_for_returning_players":false,
      "max_heartbeats_per_second":60,
      "max_players":0,
      "max_upload_in_kilobytes_per_second":0,
      "max_upload_slots":5,
      "maximum_segment_size":100,
      "maximum_segment_size_peer_count":10,
      "minimum_latency_in_ticks":0,
      "minimum_segment_size":25,
      "minimum_segment_size_peer_count":20,
      "name":"factorio.jdmarble.com",
      "non_blocking_saving":false,
      "only_admins_can_pause_the_game":true,
      "require_user_verification":true,
      "tags":[],
      "visibility":{"lan":true,"public":false}
    }
  server-adminlist.json: |
    ["BigGeneric","midorikid"]
  server-whitelist.json: |
    ["BigGeneric","midorikid"]
