---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-config.yaml
  - namespace-factorio.yaml
  - pvc-datadir.yaml
  - service-factorio.yaml
  - statefulset-factorio.yaml
