---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: factorio
  name: datadir
  labels:
    app.kubernetes.io/instance: factorio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "safe"
