---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: factorio
  name: factorio
  labels:
    app.kubernetes.io/instance: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: factorio
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: factorio
    spec:
      containers:
        - name: server
          image: "ghcr.io/goofball222/factorio:2.0.14@sha256:5aec0b49692224b7b885c1b672171d6b31537cde12fbcb8f65a4e7828fb147c8"
          imagePullPolicy: Always
          command:
            - "/opt/factorio/bin/x64/factorio"
          args:
            - "--start-server=/factorio/saves/server.zip"
            - "--server-settings=/factorio/config/server-settings.json"
            - "--server-adminlist=/factorio/config/server-adminlist.json"
            - "--use-server-whitelist=true"
            - "--server-whitelist=/factorio/config/server-whitelist.json"
            - "--rcon-port=27015"
            - "--rcon-password=rcon_is_not_exposed_externally"
          livenessProbe:
            tcpSocket:
              port: rcon
          readinessProbe:
            tcpSocket:
              port: rcon
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: factorio
              containerPort: 31497
              protocol: UDP
            - name: rcon
              containerPort: 27015
              protocol: TCP
          resources:
            requests:
              cpu: 1500m
              memory: 2Gi
            limits:
              cpu: 8
              memory: 16Gi
          volumeMounts:
            - name: datadir
              mountPath: /factorio
            - name: config
              mountPath: /factorio/config
      volumes:
        - name: game-password
          secret:
            secretName: game-password
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
        - name: config
          configMap:
            name: config
      securityContext:
        runAsUser: 11845
        runAsGroup: 11845
        fsGroup: 11845
