---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kube-system
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: e14s-5wr04w1.jdmarble.net
  share: "/mnt/front/pv"
reclaimPolicy: Delete
volumeBindingMode: Immediate