---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: pelican
  name: pelican-redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: redis-password
      remoteRef:
        key: pelican_redis
