---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: pelican
  name: pelican-redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: pelican_redis
      remoteRef:
        key: pelican_redis
  target:
    template:
      data:
        redis-password: "{{ .pelican_redis }}"
        requirepass-flagfile.txt: |
          --requirepass={{ .pelican_redis }}
