---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: pelican
  name: rclone-sqlite
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: account
      remoteRef:
        key: pelican_b2-account
    - secretKey: key
      remoteRef:
        key: pelican_b2-key
  target:
    template:
      data:
        rclone.conf: |
          [net-jdmarble-pelican-sqlite]
          type = b2
          account = {{ .account }}
          key = {{ .key }}
          hard_delete = true
