---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-dragonfly.yaml
  - deployment-pelican.yaml
  - httproute-pelican.yaml
  - namespace-pelican.yaml
  - pvc-sqlite.yaml
  - replicationdestination-sqlite.yaml
  - replicationsource-sqlite.yaml
  - sealedsecret-rclone-destination-sqlite.yaml
  - sealedsecret-rclone-source-sqlite.yaml
  - secret-pelican-redis.yaml
  - service-dragonfly.yaml
  - service-pelican.yaml

configMapGenerator:
  - namespace: pelican
    name: config
    files:
      - configs/Caddyfile
generatorOptions:
  disableNameSuffixHash: true
