---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  namespace: pelican
  name: sqlite
spec:
  sourcePVC: sqlite
  trigger:
    # Synchronize every day at 0135 hours
    schedule: "35 1 * * *"
  rclone:
    rcloneConfig: rclone-sqlite
    rcloneConfigSection: net-jdmarble-pelican
    rcloneDestPath: "net-jdmarble-pelican"
    copyMethod: Clone
