---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone-source-sqlite
  namespace: pelican
spec:
  encryptedData:
    rclone.conf: AgBE0cCfgarx6VLsArK07xvDhfXLnKFXbVu1CEQclkyk8BUVoOkALZiX72TpJlXOZcYzlgT7rfNz8Nco54i27xBmiolXbsHvfD7MGB+ow70wIyHyiZXddioGPBdz3SUsd8eQ8vruV/QcsgMqRBEqXu3P1GSicuTvaYppIpsrO6V7g0RrGz1v+zENBEI8xsHDc+jaA0O+frln68AypPL8nKELG8u60ESkx/obikzBcFv5sr9QgPH8Szkrw+gXkrRFVTyrIQpGxBwEVCz5LCtaAHoPQKl8suWw31cUdZ6mDsCoYVdhnGLqnzNrpo3W8gKIB4aArfFBpiiYJDtwJdksk+sfsEgb7fmhMr2l78+mywv3kBgmH5aU8PrtK8koqx8y1+7bhir+QWLRk2AgjbZBz4fvwsj9J9QHZqUgLi+JlVmRWNP1Otg8zKbQVIAbpV1hUF8dr2qW9UV+tLsldCIWCywzHZK5PHcA63ItbBD63yU1fwDCrjPG6282JMMF08PGhomhB0Rm+PqVGVqIGUyHZfWnd+aJU6POq8ZBZEekEeRZuz4hLGfZHg3PSYhGQyVtHpAcNPUos9+0fa9VsFu4gIsFytGmtlph+JuKVySDO/yu30FlwUDeLFXNtkHxaamXegtc7hUKAQWr27aNs4NyTwpzhzbOFOuR3W0Izv7f0FwzqNVfm3riu4KZDFOlqUuXt5b7Ikb8HmTfCgUDUNpgq3Rd269FoYvB3byZIGtqUdpSoF2Mi/WCkf8mZy3K1dO2PwOo6ldT59vg9m6VdEm5tr/q2l+zoSbynZcFvqJVwWAgLv7XH5MXriXM4PTOV5qPHswNIL8EcKI7giSjkRAYKFCwvKcu+2zAGoOVHiLbAZtpU0mTdLpF8lxT3g==
  template:
    metadata:
      creationTimestamp: null
      name: rclone-source-sqlite
      namespace: pelican
