---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # I'm installing Cilium's chart from Kustomize.
  kustomize.buildOptions: --enable-helm --helm-kube-version=1.30.3
  # CiliumIdentity
  #
  # https://docs.cilium.io/en/latest/configuration/argocd-issues/#solution
  # The `CiliumIdentity`s get created for each `Service` and inherit labels
  # including the one used by ArgoCD to identify managed resources.
  # We need to tell ArgoCD to ignore the Cilium managed resources.
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
