# Allow ArgoCD pods to run on control-plane nodes.
# This is done under the assumption that ArgoCD is "critical infrastructure".
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-deployments-in-namespace  # must have a name for patch to parse
spec:
  template:
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
