---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: argocd
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.9/manifests/core-install.yaml
  - argocd-application.yaml
  - cert-manager-application.yaml
  - external-dns-application.yaml
  - external-snapshotter-application.yaml
  - jellyfin-application.yaml
  - kanidm-application.yaml
  - kubelet-serving-cert-approver-application.yaml
  - longhorn-application.yaml
  - mealie-application.yaml
  - metallb-application.yaml
  - metrics-server-application.yaml
  - nfs-server-application.yaml
  - nginx-gateway-application.yaml
  - sealed-secrets-application.yaml
  - volsync-application.yaml

patches:
  - path: control-plane-toleration-deployment-patch.yaml
    target:
      kind: Deployment
  - path: control-plane-toleration-statefulset-patch.yaml
