---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: argocd
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.3/manifests/install.yaml
  - appproject-default.yaml
  - argocd-application.yaml
  - authelia-application.yaml
  - cert-manager-application.yaml
  - cilium-application.yaml
  - external-dns-application.yaml
  - external-snapshotter-application.yaml
  - httproute.yaml
  - homepage-application.yaml
  - jellyfin-application.yaml
  - kanidm-application.yaml
  - kubelet-serving-cert-approver-application.yaml
  - longhorn-application.yaml
  - mealie-application.yaml
  - metallb-application.yaml
  - metrics-server-application.yaml
  - nfs-server-application.yaml
  - sealedsecret-oidc-client.yaml
  - sealed-secrets-application.yaml
  - volsync-application.yaml

patches:
  - path: cilium-patch.yaml
  - path: oidc-patch.yaml
  - path: resources-patch.yaml
  - path: security-patch.yaml
  - path: server-insecure-patch.yaml
  - path: control-plane-toleration-deployment-patch.yaml
    target:
      kind: Deployment
  - path: control-plane-toleration-statefulset-patch.yaml
  - path: updated-kustomize-patch.yaml
  - path: delete-dex/deployment-patch.yaml
  - path: delete-dex/networkpolicy-patch.yaml
  - path: delete-dex/role-patch.yaml
  - path: delete-dex/rolebinding-patch.yaml
  - path: delete-dex/service-patch.yaml
  - path: delete-dex/serviceaccount-patch.yaml

images:
  - name: quay.io/argoproj/argocd
    newTag: v2.12.3@sha256:68894064bc381c19ea951029510aa614bd26bf46c2ec65ea445c7d8d095a9417
  - name: alpine
    newName: docker.io/library/alpine
    newTag: 3.8@sha256:2bb501e6173d9d006e56de5bce2720eb06396803300fe1687b58a7ff32bf4c14
  - name: redis
    newName: docker.io/library/redis
    newTag: 7.0.15-alpine@sha256:c9d92d840fd011c908f040592857c724ae6d877f2aba5c40ad963276507386b2
