---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: argocd
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.9/manifests/core-install.yaml
  - appproject-default.yaml
  - argocd-application.yaml
  - cert-manager-application.yaml
  - cilium-application.yaml
  - external-dns-application.yaml
  - external-snapshotter-application.yaml
  - homepage-application.yaml
  - jellyfin-application.yaml
  - kanidm-application.yaml
  - kubelet-serving-cert-approver-application.yaml
  - longhorn-application.yaml
  - mealie-application.yaml
  - metallb-application.yaml
  - metrics-server-application.yaml
  - nfs-server-application.yaml
  - sealed-secrets-application.yaml
  - volsync-application.yaml

patches:
  # Applying this as a patch to override the default, empty one.
  - path: configmap-argocd-cm.yaml
  - path: control-plane-toleration-deployment-patch.yaml
    target:
      kind: Deployment
  - path: control-plane-toleration-statefulset-patch.yaml
  - path: updated-kustomize-patch.yaml
