---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  source:
    repoURL: https://github.com/jdmarble/happyfold.git
    targetRevision: HEAD
    path: apps/metallb
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - "/spec/conversion/webhook/clientConfig/caBundle"
