---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  source:
    repoURL: https://github.com/jdmarble/happyfold.git
    targetRevision: HEAD
    path: apps/nginx-gateway
