---
# https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#existing-oidc-provider
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.jdmarble.net
  oidc.config: |
    name: Authelia
    issuer: https://auth.jdmarble.net
    clientID: argocd
    clientSecret: $oidc-client:oidc.authelia.clientSecret
    requestedScopes:
      - "openid"
      - "profile"
      - "email"
      - "groups"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  scopes: "[groups, email]"
  policy.csv: |
    g, admins, role:admin
